// B2.7 + S10: Stripe webhook handler.
//
// Why we need this:
//   The pre-B2.7 code "confirmed" payments by trusting the client to call
//   `createFeaturedJobCharge` after a successful Stripe Checkout v2 token,
//   which is forgeable. With Checkout Sessions we never trust the browser
//   for the payment outcome; the truth comes from Stripe's signed webhook.
//
// Idempotency:
//   Stripe will retry webhooks until it sees a 2xx, possibly delivering the
//   same event multiple times. The Jobs.update selector includes
//   `featuredChargeHistory: { $ne: session.id }`, so a replay does nothing.
//
// Body-parsing:
//   We use `WebApp.rawConnectHandlers` — which runs BEFORE Meteor's JSON
//   body parser — so we can give Stripe the exact bytes it signed. Parsed
//   JSON would have key reordering / whitespace differences and the
//   signature check would fail.
//
// PENDING EXTERNAL TESTING:
//   The signature path can only be exercised end-to-end with a real Stripe
//   account: `stripe listen --forward-to localhost:3000/_stripe/webhook`
//   plus a sandbox checkout. See FIXES_PLAN.md > Pending external testing.

var WEBHOOK_PATH = '/_stripe/webhook';

function readRawBody(req) {
  return new Promise(function(resolve, reject) {
    var chunks = [];
    req.on('data', function(c) { chunks.push(c); });
    req.on('end', function() { resolve(Buffer.concat(chunks)); });
    req.on('error', reject);
  });
}

function setFeaturedFromSession(session) {
  var meta = session.metadata || {};
  var jobId = meta.jobId;
  var extendedThroughIso = meta.extendedThrough;

  if (!jobId || !extendedThroughIso) {
    log.warn('stripe.webhook.checkout_missing_metadata', {
      sessionId: session.id
    });
    return;
  }

  var extendedThrough = new Date(extendedThroughIso);
  if (isNaN(extendedThrough.getTime())) {
    log.warn('stripe.webhook.invalid_extended_through', { sessionId: session.id });
    return;
  }

  // Atomic + idempotent: the $ne guard means a re-delivered webhook is a
  // no-op (Mongo update returns 0 docs touched). The $slice cap bounds
  // history at the last 50 charge ids per job so a long-running listing
  // doesn't accumulate an unbounded array.
  var updated = Jobs.update(
    { _id: jobId, featuredChargeHistory: { $ne: session.id } },
    {
      $set: { featuredThrough: extendedThrough },
      $push: {
        featuredChargeHistory: {
          $each: [session.id],
          $slice: -50
        }
      }
    }
  );

  log.info('stripe.webhook.checkout_completed', {
    sessionId: session.id,
    jobId: jobId,
    updated: updated,
    extendedThrough: extendedThrough.toISOString()
  });
}

// A9.39 — revokeFeatured used to apply the revoke unconditionally. That meant
// a duplicate webhook delivery for charge.refunded would push a second
// `revoked:...` entry into featuredChargeHistory each time. Worse, the
// revoked-at marker would be overwritten with a fresh `new Date(0)` (a
// no-op for the date itself, but it kept tripping the audit-log fan-out
// elsewhere). Short-circuit when the job is already non-featured AND the
// matching revoke marker already exists.
function revokeFeatured(jobId, reason, eventId) {
  if (!jobId) return;
  var marker = 'revoked:' + reason + ':' + (eventId || 'unknown');
  var existing = Jobs.findOne(
    { _id: jobId },
    { fields: { featuredThrough: 1, featuredChargeHistory: 1 } }
  );
  if (!existing) {
    log.warn('stripe.webhook.revoke_unknown_job', { jobId: jobId, reason: reason });
    return;
  }
  var alreadyRevoked = existing.featuredThrough && existing.featuredThrough.getTime() <= Date.now();
  var alreadyLogged = (existing.featuredChargeHistory || []).indexOf(marker) !== -1;
  if (alreadyRevoked && alreadyLogged) {
    log.info('stripe.webhook.revoke_idempotent_skip', {
      jobId: jobId,
      reason: reason,
      eventId: eventId
    });
    return;
  }

  // featuredThrough in the past means "not featured". Same $slice cap
  // as setFeaturedFromSession to bound the audit array.
  Jobs.update({ _id: jobId, featuredChargeHistory: { $ne: marker } }, {
    $set: { featuredThrough: new Date(0) },
    $push: {
      featuredChargeHistory: {
        $each: [marker],
        $slice: -50
      }
    }
  });
  log.warn('stripe.webhook.featured_revoked', {
    jobId: jobId,
    reason: reason,
    eventId: eventId
  });
}

function jobIdFromCharge(charge) {
  // Charges generated by a Checkout Session expose the session via
  // `charge.metadata` only when we copied it across. As a fallback,
  // look up by payment intent id stored in featuredChargeHistory in
  // future iterations. For now we rely on metadata.
  return (charge && charge.metadata && charge.metadata.jobId) || null;
}

function handleEvent(event) {
  switch (event.type) {
    case 'checkout.session.completed':
      setFeaturedFromSession(event.data.object);
      break;
    case 'checkout.session.async_payment_succeeded':
      // A9.10 — some payment methods (SEPA debit, OXXO, Konbini, certain BR
      // boleto flows) resolve hours-to-days after checkout completes. The
      // session emits `completed` immediately with payment_status="unpaid",
      // then later `async_payment_succeeded` with payment_status="paid".
      // We previously only listened for `completed`, so jobs paid by an
      // async method silently stayed un-featured. Re-running
      // setFeaturedFromSession is safe because the Jobs.update guard is
      // keyed on session.id.
      setFeaturedFromSession(event.data.object);
      break;
    case 'checkout.session.async_payment_failed':
      // The async method declined. The session was never paid; clear any
      // optimistic featured state. metadata still rides on the session.
      revokeFeatured(
        (event.data.object.metadata || {}).jobId,
        'async_payment_failed',
        event.id
      );
      break;
    case 'charge.refunded':
      revokeFeatured(jobIdFromCharge(event.data.object), 'refund', event.id);
      break;
    case 'charge.dispute.created':
      revokeFeatured(jobIdFromCharge(event.data.object), 'dispute', event.id);
      break;
    default:
      // Ignore — Stripe sends many events we don't care about.
      break;
  }
}

Meteor.startup(function() {
  if (typeof WebApp === 'undefined' || !WebApp.rawConnectHandlers) {
    log.warn('stripe.webhook.no_rawconnecthandlers');
    return;
  }

  WebApp.rawConnectHandlers.use(WEBHOOK_PATH, Meteor.bindEnvironment(function(req, res) {
    if (req.method !== 'POST') {
      res.writeHead(405, { 'Content-Type': 'text/plain' });
      res.end('Method Not Allowed');
      return;
    }

    if (!Stripe) {
      res.writeHead(503, { 'Content-Type': 'text/plain' });
      res.end('Stripe not configured');
      return;
    }

    var webhookSecret = process.env.STRIPE_WEBHOOK_SECRET ||
      (Meteor.settings.private &&
                         Meteor.settings.private.stripe &&
                         Meteor.settings.private.stripe.webhookSecret);
    if (!webhookSecret) {
      // Without a secret we cannot trust the request. Failing closed is
      // safer than processing forged events.
      res.writeHead(503, { 'Content-Type': 'text/plain' });
      res.end('Webhook secret not configured');
      return;
    }

    readRawBody(req).then(Meteor.bindEnvironment(function(rawBody) {
      var sig = req.headers['stripe-signature'];
      var event;
      try {
        event = Stripe.webhooks.constructEvent(rawBody, sig, webhookSecret);
      } catch (e) {
        log.warn('stripe.webhook.signature_verification_failed', { error: e && e.message });
        res.writeHead(400, { 'Content-Type': 'text/plain' });
        res.end('Webhook signature verification failed');
        return;
      }

      try {
        handleEvent(event);
      } catch (e) {
        // Log but still 200 — repeated webhook retries for the same
        // handler-internal bug just stack up noise. We'd rather see the
        // first error in our logs.
        log.error('stripe.webhook.handler_error', {
          type: event.type,
          error: e && e.message,
          stack: e && e.stack
        });
      }

      res.writeHead(200, { 'Content-Type': 'text/plain' });
      res.end('ok');
    })).catch(function(e) {
      log.error('stripe.webhook.body_read_error', { error: e && e.message });
      res.writeHead(400, { 'Content-Type': 'text/plain' });
      res.end('Could not read body');
    });
  }));
});
